### ISSUE TITLE
Index Page requires obvious/stylized navigation

### ISSUE THREAD

**Issue by Cascadia-ScottMaxwell** [TeamKismet/bit-286-mathgame#6]
On startup, it should be easier to find the links to navigate to the student and teacher login pages

**Comment by HaakonJ** [comment]
I have done some work to make the start up page look more like it actually applies to our application. Tomorrow I will hopefully be done with that.

**Comment by HaakonJ** [comment]
Any obvious navigation changes have been made on Haakon's branch as well as the master.
